version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://users_service:8081
    depends_on:
      - users_service
    networks:
      - internal

  users_service:
    build: ./users_service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=users_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_db
    depends_on:
      - users_db
    networks:
      - internal

  events_service:
    build: ./events_service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=events_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=events_db
    depends_on:
      - events_db
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks: [internal]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on: [zookeeper]
    networks: [internal]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports: ["9092:9092"]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports: ["8082:8080"]
    depends_on: [kafka]
    networks: [internal]
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  users_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    volumes:
      - ./users_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  events_db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events_db
    volumes:
      - ./events_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

networks:
  internal:
